### ISSUE TITLE
CreateDirectory MakeDirectory

### ISSUE THREAD

**Issue by smnpaorg** [jmlopez-rod/ApplicationMaker#5]
I keep receiving the following error when attempting to call `NewApplication["test"]`.

It occurs in both M9 and M10 in W7.

```
CreateDirectory::ioarg: Argument in         
CreateDirectory[\C:\Users\a\AppData\Roaming\Mathematica\Applications\test2\Documentation] is not valid for I/O operation. >>
```

A quick fix is to replace `CreateDirectory[tmp]` with `CreateDirectory[StringTrim[tmp, "\\"]]` in the `MakeDirectory` function for at least W7.

The issue comes from `FileNameJoin[{root, start, sub[[nm, i]]}]` -> `FileNameJoin[{"", FileNameJoin[{ $UserBaseDirectory, "Applications"}],
   "test"}]` turning into `"\\C:\\Users\\a\\AppData\\Roaming\\Mathematica\\Applications\\test"`.

This is not an issue in Linux and Mac because both `\\` and `//` are simply viewed as root.

**Comment by jmlopez-rod** [comment]
I think you will have to tackle this one since I have no Windows machine. Perhaps make an if statement doing your fix if it is run under Windows?

**Comment by akater** [comment]
Actually, this was one of the reasons I wrote to @jmlopez-rod initially, which led to creation of this repo. I have a version of ApplicationMaker.m where the issue seems to be fixed. It works on my Windows installation.

However, it also has other things rewritten (I tried my best to write programs with equivalent effects, of course), and the overall style is a bit nonstandard. I'm still ignorant of Git way of dealing with this, so I'll just propose a pull request, as soon as I find out how to do that.

**Comment by smnpaorg** [comment]
@akater @jmlopez-rod 
I'll admit you thoroughly modified the code, I'm still trying to figure out exactly what you did.
Here is a quick fix in case you aren't interested in merging all of akataer changes.

```
 If[$OperatingSystem == "Windows", StringTrim[tmp, "\\"], tmp]
```

**Comment by akater** [comment]
I was making those changes when this repository hadn't yet existed. I can subdivide them into several steps, if needed. Just hoped that maintainer could easily verify the equivalence by running several simple tests.

**Comment by jmlopez-rod** [comment]
I think it is time to start creating several branches. For one, we can create a develop branch were the code will be in review. Once enough futures are fixed or added then we merge them into the master branch. So for now if you guys have changes that make it work under windows send them in. I'll try to test them make sure that they still work under OS X and Linux.

For now please use the develop branch I created to update the code. Also @smnpaorg, I'm making you a collaborator. Once the code has made significant changes and we may want to give the application a different version and we'll release it to the master branch.

**Comment by akater** [comment]
Directory tree works in my Windows installation. Provided this is indeed the tree you wanted to create. — I remind you that I just copied the layout from existing application dirs, not from your version of `NewApplication`.

Concerning other changes… I don't yet know what exactly should other functions in this package actually do. There's no help for `ChangeNotebookSettings`, and no usage messages, as well, for example.

**Comment by smnpaorg** [comment]
@akater 
You merged your changes into ApplicationMaker.m but not the ApplicationMaker.nb.

I have manually added the edit to the NB but it has introduced a major inconsistency for those that might download the package from the git repository.

I would like to patch a couple errors but a system might need to be established for what files we might choose to edit or not.  Are you using the Wolfram Workbench?

**Comment by akater** [comment]
1) @jmlopez-rod decided to commit everything to dev-branch. I'm going to close my fork now and start working with shared repository. (Sorry, I should have done it yesterday at least but was a bit busy.)

2) .nb's are irrelevant, I proposed to delete them altogether, for they are of no use.

**Comment by smnpaorg** [comment]
@akater 

.nb's allow you to format the code prior to saving the file witch automatically generates the .m files.

For me I need formatting to understand the layout of the code which .m don't have.  Wolfram WorkBench I believe helps with formatting but I haven't paid for such currently.

**Comment by akater** [comment]
@smnpaorg I decided to remove .nb's, not @jmlopez-rod 
I use FrontEnd, and I also try to indent definitions carefully, and put sections everywhere. I edit .m files there directly. Did you take a look at .m's I had commited in the FrontEnd?

Is this the proper thread to discuss it, though? I promised @jmlopez-rod that we shall not flood. :-)

**Comment by akater** [comment]
@smnpaorg This is how it looks for me: https://imgur.com/MlBFWMg You'll see pretty much the same, modulo color scheme. Aside from commas in the beginning of lines [I guess], what is it that discomforts you? Do you prefer wider indents?

I have a commit staged for this branch, it removes .nb's. If we don't come to agreement, I'll make changes to notebooks. However, I've spent some time writing Mma packages, and came to conclusion that it's better to work with .m files directly if you don't have any tools in FrontEnd besides its default ones. I'm ready to back this with some facts but not in this thread directly. (I already feel a bit guilty about offtopics here.)

**Comment by smnpaorg** [comment]
@akater 
Here is a separate issue on my own branch so we stop pigging jmlopez https://github.com/smnpaorg/ApplicationMake/issues/1
I don't get that view at all.

**Comment by smnpaorg** [comment]
@akater 
This is my view http://i.imgur.com/r0Ntkel.png?1

again leave a comment here https://github.com/smnpaorg/ApplicationMake/issues/1 if you want to stop pinging jmlopez-rod
